# Generated by Django 4.2 on 2023-04-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('signature', models.CharField(default="keep on rockin'", max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
